# Configuraci칩n del Servidor con atributo port  Puerto por defecto de Eureka
server:
  port: 8761

# Configuraci칩n de Spring Boot
spring:
  application:
    name: msvc-eureka

# Configuraci칩n de Eureka
eureka:
  instance:
    hostname: localhost
  client:
    # para que no se auto arranque o se registre dentro de si mismo.
    register-with-eureka: false
    fetch-registry: false
    server-url:
      # ruta por defecto con variable referenciada para mejor mantenimiento (est치 arriba)
      defaultZone: "http://localhost:${server.port}/eureka/"
